#!/usr/bin/env zsh

stow_folders=(${(s:,:)STOW_FOLDERS})

# Navigate to dotfiles directory
if pushd $DOTFILES; then
    for folder in $stow_folders; do
        echo "Stowing $folder..."
        
        # Unstow and restow the folder
        if ! stow -D -d "$DOTFILES" -t "$HOME" "$folder"; then
            echo "Error unstowing $folder. Aborting."
            exit 1
        fi
        if ! stow -d "$DOTFILES" -t "$HOME" "$folder"; then
            echo "Error stowing $folder. Aborting."
            exit 1
        fi
    done
    popd
else
    echo "Error navigating to $DOTFILES. Aborting."
    exit 1
fi